# Generated by Django 4.0.3 on 2022-04-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombre')),
                ('tarifa_por_noche', models.CharField(max_length=100, verbose_name='Tarifa por Noche')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'aulas',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=35, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'db_table': 'propietarios',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca del Alimento')),
                ('categoria', models.CharField(choices=[('canino', 'Canino'), ('felino', 'Felino'), ('ave', 'Ave')], default='canino', max_length=15, verbose_name='Categoria del Alimento')),
                ('nombre_alimento', models.CharField(max_length=50, verbose_name='Nombre del Alimento')),
                ('precio', models.CharField(max_length=100, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='masculino', max_length=1)),
                ('categoria', models.CharField(choices=[('canino', 'Canino'), ('felino', 'Felino'), ('ave', 'Ave')], default='canino', max_length=15)),
                ('raza', models.CharField(max_length=30, null=b'I00\n')),
                ('fecha_entrada', models.DateField(null=b'I00\n')),
                ('fecha_salida', models.DateField(null=b'I00\n')),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mascota.aulas')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mascota.propietario')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mascota.servicios')),
            ],
            options={
                'db_table': 'mascotas',
            },
        ),
    ]
