# Generated by Django 4.0.3 on 2022-04-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='tarifa_por_noche',
            field=models.IntegerField(verbose_name='Tarifa por Noche'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
